griffinbank/rules_clojure

README.md, src/rules_clojure/gen_build.clj
Allows extra-deps for multiple targets, based on the rules for
specifying wildcards in bazel.
Note: It is not clear whether supporting :* and :all-targets for
matching extra-deps is the right thing to do, the distinction between
:all and :all-targets is the distinction between rules and (rules + files)
=> Handle wildcard labels in :extra-deps.

rules/tools_deps.bzl, toolchains.bzl
My main motivation here is that there's been a number of concurrency fixes to maven downloads.
=> Bump Clojure versions

src/rules_clojure/gen_build.clj
Sorting the output of `fs/ls` makes the generated files output more repeatable
=> more stable output for BUILD.bazel fields

src/rules_clojure/gen_build.clj
In my last PR: https://github.com/griffinbank/rules_clojure/pull/7/files#diff-7425d04e2b9d01ea954bb5deef8941e306d1ddae09b2995068d4476be1e93b7aL714
I removed the use of `distinct`: this was incorrect!
From the list of `paths`, calling `fs/basename` can return the same base name (in fact there is a `group-by` just above using this fact).
This would result in incorrect behavior when there is ex. a `code.clj` and `code.cljs` file in the same directory
=> fix: put distinct back

rules.bzl, rules/jar.bzl, src/rules_clojure/BUILD.bazel, src/rules_clojure/gen_build.clj
Prevent rules_clojure dependencies from leaking into the application, and clobbering e.g. the version of Clojure in use by the application.
=> One clojure version to rule them all

rules.bzl
The compiler expects "-co" to have only one file or EDN
=> Append ["-co", file] for each compile_opts_files

rules/tools_deps.bzl
=> Quote :exclude-nses when passing to ns-loader

java/rules_clojure/BUILD.bazel
Not clear how much we actually need, and whether we should even put a ceiling on this. I suppose if we're using more than 1GB then something's probably not working as expected. 500MB is _a lot_ already - we should probably look into why that's getting exceeded.
=> bump max metaspace to 1g

README.md, src/rules_clojure/bootstrap_worker.clj, src/rules_clojure/jar.clj
Use `rules-clojure.parse` rather than `c.t.n.parse` in jar.clj. We were already using rules-clojure.parse (used to fix handling of `:as-alias` in 1.11), in gen-build, but weren't using it in rules-clojure.jar. 
This fixes a bug where bazel dependencies were incorrect in sandboxed build modes (i.e. non-worker and remote). The bug doesn't manifest when using the persistent worker, because workers are not sandboxed.
=> Use rules-clojure.parse

.gitignore, rules/tools_deps.bzl
Sometimes `rules_clojure` fails with an error in `tools_deps.bzl/_run_gen_build`, which claims that it couldn't copy to `/root/.clojure/deps.edn` (i.e. `~/.clojure/deps.edn` for `root`), because the file already exists.
This appears to be a step in the `/usr/local/bin/clojure` script. When run, it checks for the existence of `~/.clojure/deps.edn` (by default), and copies a file into there from the install dir if not.
My theory is that multiple `clojure` runs are occurring at the same time in the same container. When that happens, there can be a race condition where they both detect that the file is not present, and then both try to copy the example file in. One wins, the other gets an error.
To prevent this race condition due to the behaviour of `cp`, we now set up these files within the …
=> Fix parallel bazel executions on CI

rules/jar.bzl, src/rules_clojure/worker.clj
According to the docs at
https://bazel.build/remote/persistent#implementation, the protobuf definition for persistent workers uses snake case, but the JSON implementation uses camel case. It also specifies that the JSON version should ignore any fields it gets that it doesn't recognise.
Given `:exit_code` was specified in our response map, instead of `:exitCode`, I believe Bazel was never detecting the exit code from a persistent worker job, and was just defaulting to the assumption that the build succeeded. This is why the compilation failure in the code the data team is working on for the chart of accounts migration etc managed to get into the primary branch.
=> Fix `persistent-worker` exit code

src/rules_clojure/BUILD
Increase heap and metaspace as limits have been breached
=> Bump worker MaxMetaspaceSize to 2g

src/rules_clojure/persistent_classloader.clj
Also discard the classloader when the namespace being compiled contains deftypes. This line used to be in main before #28, but I thought it wasn't necessary. I was wrong.
=> Also discard on deftypes

src/rules_clojure/compile.clj, src/rules_clojure/persistent_classloader.clj
=> Discard the environment when the namespace is already loaded

rules/tools_deps.bzl
Using `1.11.1.1347` complains about an incorrect SHA
Validated the changes with:
```
curl --silent $URL | shasum -a 256
```
for both `CLJ_VERSIONS_LINUX` and `CLJ_VERSIONS_MAC` that are in the file
=> Fix the sha for Linux 1.11.1.1347

src/rules_clojure/jar.clj
Tweak on #38 .  Unlike bazel compiling `.java` to `.class`, we can't assume that rules clojure touched every .clj file on the classpath. Therefore move the last modified time of rules_clojure produced files to the future, to guarantee it will be picked up.
=> arohner Stable jar

src/rules_clojure/jar.clj
same as #35, except uses fixed file modification times, with the hope that it results in deterministic jars getting built.
=> stable jar

README.md, rules.bzl, rules/jar.bzl
Previously we relied on a bazel `java_binary` to start the worker. That precludes passing `:jvm_opts`, which among other things prevents compiling code that requires `--enable-preview`. This reworks worker startup, and enables passing `:jvm_opts` to `clojure_library`.
=> Improve worker startup

rules.bzl, rules/jar.bzl, src/rules_clojure/worker.clj
The previous PR introduce a performance regression which broke persistent workers, resulting in slow compilations.
I was calling `ctx.attr._jdk[java_common.JavaRuntimeInfo].java_executable_exec_path` directly because I thought `java_binary` didn't support jvm_flags as an argument. For reasons I don't understand, bazel refuses to allow that to be a persistent worker. 
Reading the actual shell script shows that it does support `--jvm_flag=`, so use the old style java_binary and pass `--jvm_flag` to it.
=> Fix performance regression

src/rules_clojure/worker.clj
I added this warning after fixing #43. When running locally, the warning remains a good idea. However, under RBE remote persistent workers are not supported, which means fires uselessly on every target under RBE, and I'm not aware of a way to distinguish local from RBE operation.
=> Remove noisy warning

src/rules_clojure/gen_build.clj
We weren't generating `clojure_test` targets for .cljc files.
=> Also generate `clojure_test` for .cljc files

src/rules_clojure/BUILD
When building a large application:
- the max allowed heap size is used
- max allowed metaspace size is exceeded and the build fails with an `OutOfMemoryError`.
Increasing MaxMetaspaceSize may just be a temporary fix. It's possible we're preventing garbage collection of loaded classes, but I haven't investigated this yet.
=> double Xmx, MaxMetaspaceSize

src/rules_clojure/fs.clj, src/rules_clojure/gen_build.clj
Adds type hints to avoid reflection that contributed significantly to runtime of `gen_srcs`. In my benchmark on a large application, runtime goes from 14s to 9.7s.
=> avoid reflection

src/rules_clojure/gen_build.clj
much of the time in `bazel run //:gen_srcs` is IO and so can be parallelised for a significant speedup.  parallelising the calls to `gen-dir` speeds up my benchmark of `-main` from ~7s to 5s
the overall `bazel run //:gen_srcs` runtime drops from 9.7s to 7.2s (although these are quite variable).
=> parallelise gen-dir calls

src/rules_clojure/testrunner.clj
This uses sun.misc.Signal, which has been granted an [exemption](https://openjdk.org/jeps/260) for now.  It's important to _only_ hook SIGTERM and not general exits, which is why I'm not using a shutdown hook here.
There is a jnr-signals package, but I figured that bringing in more dependencies was a lot of work relative to just using seemingly safe sun.misc.Signal*
This is important for debugging _where_ in your test there's a timeout.
=> Dump threads on test timeout
